const root = document.querySelector("#relay-root");
const endpoint = String(window.OVER39_SUPABASE_RELAY_URL || "").trim();
const relayQuery = new URLSearchParams(location.search);
const token = relayQuery.get("t") || "";
const interfaceLanguage = relayQuery.get("lang") || localStorage.getItem("over39-interface-language") || navigator.language || "ko";
const interfaceLanguageCode = String(interfaceLanguage || "").replace(/^zh(?:[-_])?cn$/i, "zh-Hans").replace(/^zh(?:[-_])?(tw|hk)$/i, "zh-Hant");
const text = (value) => String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");

const copy = {
  ko: { label: "〈만 39세 이상〉 · 안부의 좌표", title: "안부의 좌표", lead: "서로 다른 기록 사이에 안부를 남깁니다. 이곳의 위치는 사람의 유형이 아니라 이번 기록에서 읽힌 방향이며, 시간이 지나거나 상황이 달라지면 달라질 수 있습니다. 도착한 원문을 먼저 읽고, 필요하면 번역을 펼쳐보세요.", reason: "이 안부가 닿은 이유", original: "원문", translation: "번역 보기", hideTranslation: "번역 접기", replyTitle: "답장을 맡길까요?", replyHelp: "답장 원문도 그대로 보존하며 연락처는 상대에게 공개하지 않습니다. 이 답장은 다음 사람에게 전할 새로운 안부로 기다릴 수 있습니다.", placeholder: "짧은 인사나 질문을 적어주세요.", pass: "이번에는 지나갈게요", withdraw: "안부 연결 철회", send: "답장 맡기기", sent: "답장을 맡겼습니다.", passed: "이번 안부는 조용히 지나갑니다.", withdrawn: "이 안부 연결을 철회했습니다.", error: "안부를 불러오지 못했습니다. 링크를 다시 확인해주세요.", loading: "안부를 불러오고 있습니다.", mine: "나의 위치", sender: "안부를 보낸 사람의 위치", senderTypes: { MAKING: "작업을 만들어 온 참여자", CONNECTING: "작업과 사람을 이어 온 참여자", READING: "작업을 읽고 기록해 온 참여자", PERFORMANCE: "공연과 연습을 이어 온 참여자", EDUCATION: "교육과 배움을 통해 문화예술을 이어 온 참여자", EVERYDAY: "생활 안에서 문화예술 활동을 이어 온 참여자", CULTURAL_RELATION: "문화예술과 관계를 이어 온 참여자" }, reasonSummary: "이 안부는 두 기록에서 가까이 나타난 방향과 역할, 고른 연결 방향을 함께 읽어 전했습니다. 이 위치는 시간이 지나거나 상황이 달라지면 달라질 수 있습니다.", sameDirection: "두 기록 모두 가까운 한 방향이 남아 있습니다.", adjacentDirection: "두 기록의 방향 가운데 일부가 이웃해 있습니다.", roleBridge: "서로 다른 역할의 자리에서 비슷한 질문이 이어졌습니다." },
  en: { label: "〈Over 39〉 · 안부의 좌표", title: "안부의 좌표", lead: "A greeting is left between different records. The position here is not a person’s fixed type: it is a direction read in this record, and it can change as time or circumstances change. Read the original first, then open the translation if you need it.", reason: "Why this greeting reached you", original: "Original", translation: "View translation", hideTranslation: "Hide translation", replyTitle: "Entrust a reply?", replyHelp: "Your original reply is preserved, and your contact details are never shown to the other participant. This reply may wait as a new greeting for the next person.", placeholder: "A short greeting or question is enough.", pass: "Pass this time", withdraw: "Withdraw this connection", send: "Entrust reply", sent: "Your reply has been entrusted.", passed: "This greeting will pass quietly this time.", withdrawn: "This greeting connection has been withdrawn.", error: "We could not open this greeting. Please check the link.", loading: "Opening the greeting.", mine: "My position", sender: "Sender’s position" },
  ja: { label: "〈39歳以上〉・便りの座標", title: "便りの座標", lead: "異なる記録のあいだに便りを残します。ここでの位置は人の固定的な類型ではなく、今回の記録から読まれた方向です。時間や状況が変われば変わることがあります。まず原文を読み、必要なら翻訳を開いてください。", reason: "この便りが届いた理由", original: "原文", translation: "翻訳を見る", hideTranslation: "翻訳を閉じる", replyTitle: "返事を託しますか？", replyHelp: "返事の原文もそのまま保管され、連絡先が相手に公開されることはありません。この返事は次の人へ届く新しい便りとして待つことがあります。", placeholder: "短い挨拶や質問を書いてください。", pass: "今回は見送る", withdraw: "このつながりを取り消す", send: "返事を託す", sent: "返事を託しました。", passed: "今回はこの便りを静かに見送ります。", withdrawn: "この便りのつながりを取り消しました。", error: "便りを開けませんでした。リンクを確認してください。", loading: "便りを開いています。", mine: "私の位置", sender: "便りを残した人の位置" },
  "zh-Hans": { label: "〈39岁以上〉· 问候坐标", title: "问候坐标", lead: "问候留在不同记录之间。这里的位置不是人的固定类型，而是从这份记录中读出的方向；时间或情况变化后，它也可能变化。请先阅读原文，需要时再展开翻译。", reason: "这封问候抵达的原因", original: "原文", translation: "查看翻译", hideTranslation: "收起翻译", replyTitle: "要托付一封回复吗？", replyHelp: "回复原文会被完整保留，联系方式不会向另一位参与者公开。这封回复可能作为新的问候等待下一位合适的参与者。", placeholder: "写下一句简短问候或问题。", pass: "这次先略过", withdraw: "撤回这次连接", send: "托付回复", sent: "已托付回复。", passed: "这封问候这次会安静地略过。", withdrawn: "已撤回这次问候连接。", error: "无法打开这封问候，请检查链接。", loading: "正在打开问候。", mine: "我的位置", sender: "留下问候者的位置" },
  "zh-Hant": { label: "〈39歲以上〉· 問候座標", title: "問候座標", lead: "問候留在不同記錄之間。這裡的位置不是人的固定類型，而是從這份記錄中讀出的方向；時間或情況改變後，它也可能改變。請先閱讀原文，需要時再展開翻譯。", reason: "這封問候抵達的原因", original: "原文", translation: "查看翻譯", hideTranslation: "收起翻譯", replyTitle: "要託付一封回覆嗎？", replyHelp: "回覆原文會被完整保留，聯絡方式不會向另一位參與者公開。這封回覆可能作為新的問候等待下一位合適的參與者。", placeholder: "寫下一句簡短問候或問題。", pass: "這次先略過", withdraw: "撤回這次連結", send: "託付回覆", sent: "已託付回覆。", passed: "這封問候這次會安靜地略過。", withdrawn: "已撤回這次問候連結。", error: "無法開啟這封問候，請檢查連結。", loading: "正在開啟問候。", mine: "我的位置", sender: "留下問候者的位置" },
  fr: { label: "〈Plus de 39 ans〉 · Coordonnées des salutations", title: "Coordonnées des salutations", lead: "Un message circule entre des récits différents. La position ici n’est pas un type fixe : c’est une direction lue dans ce récit, qui peut changer avec le temps ou les circonstances. Lisez d’abord l’original, puis ouvrez la traduction si besoin.", reason: "Pourquoi ce message vous est parvenu", original: "Original", translation: "Voir la traduction", hideTranslation: "Masquer la traduction", replyTitle: "Confier une réponse ?", replyHelp: "L’original de votre réponse est conservé et vos coordonnées ne sont jamais montrées à l’autre personne. Cette réponse peut attendre comme un nouveau message pour la personne suivante.", placeholder: "Un court bonjour ou une question suffit.", pass: "Passer cette fois", withdraw: "Retirer ce lien", send: "Confier la réponse", sent: "Votre réponse a été confiée.", passed: "Ce message passera discrètement cette fois.", withdrawn: "Ce lien de message a été retiré.", error: "Nous n’avons pas pu ouvrir ce message. Vérifiez le lien.", loading: "Ouverture du message.", mine: "Ma position", sender: "Position de la personne qui a laissé le message" },
  es: { label: "〈Mayores de 39〉 · Coordenadas de saludo", title: "Coordenadas de saludo", lead: "Un saludo queda entre registros distintos. La posición no es un tipo fijo de persona: es una dirección leída en este registro y puede cambiar con el tiempo o las circunstancias. Lea primero el original y abra la traducción si la necesita.", reason: "Por qué le llegó este saludo", original: "Original", translation: "Ver traducción", hideTranslation: "Ocultar traducción", replyTitle: "¿Quiere confiar una respuesta?", replyHelp: "El original de su respuesta se conserva y sus datos de contacto nunca se muestran a la otra persona. Esta respuesta puede esperar como un nuevo saludo para la siguiente persona.", placeholder: "Basta un saludo o una pregunta breve.", pass: "Pasar esta vez", withdraw: "Retirar esta conexión", send: "Confiar respuesta", sent: "Su respuesta ha sido confiada.", passed: "Este saludo pasará tranquilamente esta vez.", withdrawn: "Esta conexión de saludo se ha retirado.", error: "No pudimos abrir este saludo. Revise el enlace.", loading: "Abriendo el saludo.", mine: "Mi posición", sender: "Posición de quien dejó el saludo" },
  nl: { label: "〈39 jaar en ouder〉 · Groetcoördinaten", title: "Groetcoördinaten", lead: "Een groet blijft tussen verschillende records. De positie hier is geen vast type persoon: het is een richting die in dit record wordt gelezen en kan veranderen met tijd of omstandigheden. Lees eerst het origineel en open zo nodig de vertaling.", reason: "Waarom deze groet u bereikte", original: "Origineel", translation: "Vertaling bekijken", hideTranslation: "Vertaling verbergen", replyTitle: "Een antwoord toevertrouwen?", replyHelp: "De originele tekst van uw antwoord blijft bewaard en uw contactgegevens worden nooit aan de andere deelnemer getoond. Dit antwoord kan als nieuwe groet op de volgende persoon wachten.", placeholder: "Een korte groet of vraag is genoeg.", pass: "Deze keer overslaan", withdraw: "Deze verbinding intrekken", send: "Antwoord toevertrouwen", sent: "Uw antwoord is toevertrouwd.", passed: "Deze groet gaat deze keer rustig voorbij.", withdrawn: "Deze groetverbinding is ingetrokken.", error: "We konden deze groet niet openen. Controleer de link.", loading: "De groet wordt geopend.", mine: "Mijn positie", sender: "Positie van de afzender" },
  ms: { label: "〈39 tahun ke atas〉 · Koordinat Salam", title: "Koordinat Salam", lead: "Salam ditinggalkan antara rekod yang berbeza. Kedudukan di sini bukan jenis tetap seseorang: ia ialah arah yang dibaca dalam rekod ini dan boleh berubah mengikut masa atau keadaan. Baca teks asal dahulu, kemudian buka terjemahan jika perlu.", reason: "Mengapa salam ini sampai kepada anda", original: "Teks asal", translation: "Lihat terjemahan", hideTranslation: "Sembunyikan terjemahan", replyTitle: "Amanahkan balasan?", replyHelp: "Teks asal balasan anda disimpan dan maklumat hubungan tidak pernah dipaparkan kepada peserta lain. Balasan ini boleh menunggu sebagai salam baharu untuk orang seterusnya.", placeholder: "Salam atau soalan pendek sudah memadai.", pass: "Lepasi kali ini", withdraw: "Tarik balik hubungan ini", send: "Amanahkan balasan", sent: "Balasan anda telah diamanahkan.", passed: "Salam ini akan berlalu dengan tenang kali ini.", withdrawn: "Hubungan salam ini telah ditarik balik.", error: "Kami tidak dapat membuka salam ini. Sila semak pautan.", loading: "Sedang membuka salam.", mine: "Kedudukan saya", sender: "Kedudukan orang yang meninggalkan salam" },
};

// Structured v3 reason snapshots are deliberately made from category codes,
// not translated respondent text. That lets the same factual explanation be
// shown in the recipient's language while legacy v2 snapshots remain intact.
const greetingReasonCopy = {
  ko: { map: "두 기록에서 읽힌 현재 위치", sender: { MAKING: "작업을 만들어 온 참여자", CONNECTING: "작업과 사람을 이어 온 참여자", READING: "작업을 읽고 기록해 온 참여자", PERFORMANCE: "공연과 연습을 이어 온 참여자", EDUCATION: "교육과 배움을 통해 문화예술을 이어 온 참여자", EVERYDAY: "생활 안에서 문화예술 활동을 이어 온 참여자", CULTURAL_RELATION: "문화예술과 관계를 이어 온 참여자" }, summary: "이 안부는 두 기록에서 가까이 나타난 방향과 역할, 고른 연결 방향을 함께 읽어 전했습니다. 이 위치는 시간이 지나거나 상황이 달라지면 달라질 수 있습니다.", SAME_DIRECTION: "두 기록 모두 가까운 한 방향이 남아 있습니다.", ADJACENT_DIRECTION: "두 기록의 방향 가운데 일부가 이웃해 있습니다.", ROLE_BRIDGE: "서로 다른 역할의 자리에서 비슷한 질문이 이어졌습니다." },
  en: { map: "Current positions read in the two records", sender: { MAKING: "a participant who has been making work", CONNECTING: "a participant who has been connecting work and people", READING: "a participant who has been reading and documenting work", PERFORMANCE: "a participant who has been continuing performance and practice", EDUCATION: "a participant who has been continuing arts and culture through teaching and learning", EVERYDAY: "a participant who has been continuing arts and culture in everyday life", CULTURAL_RELATION: "a participant who has remained in relation with arts and culture" }, summary: "This greeting was passed on by reading the directions that appeared close in both records, the present roles, and the chosen direction of connection. This position can change with time or circumstances.", SAME_DIRECTION: "One nearby direction appears in both records.", ADJACENT_DIRECTION: "Some directions in the two records sit next to one another.", ROLE_BRIDGE: "A similar question continues from different roles." },
  ja: { map: "二つの記録から読まれた現在の位置", sender: { MAKING: "制作を続けてきた参加者", CONNECTING: "作品と人をつないできた参加者", READING: "作品を読み、記録してきた参加者", PERFORMANCE: "公演と練習を続けてきた参加者", EDUCATION: "教育と学びを通して文化芸術を続けてきた参加者", EVERYDAY: "生活の中で文化芸術活動を続けてきた参加者", CULTURAL_RELATION: "文化芸術との関係を続けてきた参加者" }, summary: "この便りは、二つの記録で近くに現れた方向、現在の役割、選ばれたつながりの方向をあわせて読んで届けられました。この位置は時間や状況によって変わることがあります。", SAME_DIRECTION: "二つの記録に近い一つの方向が残っています。", ADJACENT_DIRECTION: "二つの記録の方向の一部が隣り合っています。", ROLE_BRIDGE: "異なる役割の場所から似た問いが続いています。" },
  "zh-Hans": { map: "两份记录中读到的当前位置", sender: { MAKING: "一位持续创作的参与者", CONNECTING: "一位持续连接作品与他人的参与者", READING: "一位持续阅读并记录作品的参与者", PERFORMANCE: "一位持续表演与练习的参与者", EDUCATION: "一位通过教学与学习持续参与文化艺术的参与者", EVERYDAY: "一位在日常生活中持续参与文化艺术的参与者", CULTURAL_RELATION: "一位持续与文化艺术保持关系的参与者" }, summary: "这封问候综合阅读了两份记录中相近的方向、当前角色与所选的连接方向后送达。这个位置会随时间或情况而变化。", SAME_DIRECTION: "两份记录中都出现了一个相近的方向。", ADJACENT_DIRECTION: "两份记录中的部分方向彼此相邻。", ROLE_BRIDGE: "相似的问题从不同角色的位置延续而来。" },
  "zh-Hant": { map: "兩份記錄中讀到的目前位置", sender: { MAKING: "一位持續創作的參與者", CONNECTING: "一位持續連結作品與他人的參與者", READING: "一位持續閱讀並記錄作品的參與者", PERFORMANCE: "一位持續表演與練習的參與者", EDUCATION: "一位透過教學與學習持續參與文化藝術的參與者", EVERYDAY: "一位在日常生活中持續參與文化藝術的參與者", CULTURAL_RELATION: "一位持續與文化藝術保持關係的參與者" }, summary: "這封問候綜合閱讀了兩份記錄中相近的方向、目前角色與所選的連結方向後送達。這個位置會隨時間或情況而改變。", SAME_DIRECTION: "兩份記錄中都出現了一個相近的方向。", ADJACENT_DIRECTION: "兩份記錄中的部分方向彼此相鄰。", ROLE_BRIDGE: "相似的問題從不同角色的位置延續而來。" },
  fr: { map: "Positions actuelles lues dans les deux récits", sender: { MAKING: "une personne participante qui crée", CONNECTING: "une personne participante qui relie les œuvres et les personnes", READING: "une personne participante qui lit et documente des œuvres", PERFORMANCE: "une personne participante qui poursuit la pratique et la scène", EDUCATION: "une personne participante qui poursuit les arts et la culture par l’enseignement et l’apprentissage", EVERYDAY: "une personne participante qui poursuit les arts et la culture dans la vie quotidienne", CULTURAL_RELATION: "une personne participante qui reste en relation avec les arts et la culture" }, summary: "Cette salutation a été transmise en lisant les directions proches dans les deux récits, les rôles actuels et la direction de lien choisie. Cette position peut changer avec le temps ou les circonstances.", SAME_DIRECTION: "Une direction proche apparaît dans les deux récits.", ADJACENT_DIRECTION: "Certaines directions des deux récits sont voisines.", ROLE_BRIDGE: "Une question similaire se poursuit depuis des rôles différents." },
  es: { map: "Posiciones actuales leídas en los dos registros", sender: { MAKING: "una persona participante que ha seguido creando", CONNECTING: "una persona participante que ha conectado obras y personas", READING: "una persona participante que ha leído y documentado obras", PERFORMANCE: "una persona participante que ha seguido actuando y practicando", EDUCATION: "una persona participante que ha continuado en las artes y la cultura mediante enseñanza y aprendizaje", EVERYDAY: "una persona participante que ha continuado en las artes y la cultura en la vida cotidiana", CULTURAL_RELATION: "una persona participante que ha mantenido una relación con las artes y la cultura" }, summary: "Este saludo se entregó al leer las direcciones cercanas en ambos registros, los roles actuales y la dirección de conexión elegida. Esta posición puede cambiar con el tiempo o las circunstancias.", SAME_DIRECTION: "Una dirección cercana aparece en ambos registros.", ADJACENT_DIRECTION: "Algunas direcciones de los dos registros son vecinas.", ROLE_BRIDGE: "Una pregunta similar continúa desde roles diferentes." },
  nl: { map: "Huidige posities uit de twee records", sender: { MAKING: "een deelnemer die werk maakt", CONNECTING: "een deelnemer die werk en mensen verbindt", READING: "een deelnemer die werk leest en documenteert", PERFORMANCE: "een deelnemer die optreden en oefenen voortzet", EDUCATION: "een deelnemer die kunst en cultuur voortzet via onderwijs en leren", EVERYDAY: "een deelnemer die kunst en cultuur in het dagelijks leven voortzet", CULTURAL_RELATION: "een deelnemer die verbonden blijft met kunst en cultuur" }, summary: "Deze groet is doorgegeven door de richtingen die in beide records dichtbij verschijnen, de huidige rollen en de gekozen richting van verbinding samen te lezen. Deze positie kan veranderen met tijd of omstandigheden.", SAME_DIRECTION: "In beide records verschijnt één nabije richting.", ADJACENT_DIRECTION: "Enkele richtingen in de twee records liggen naast elkaar.", ROLE_BRIDGE: "Een vergelijkbare vraag loopt door vanuit verschillende rollen." },
  ms: { map: "Kedudukan semasa yang dibaca dalam dua rekod", sender: { MAKING: "seorang peserta yang terus menghasilkan karya", CONNECTING: "seorang peserta yang menghubungkan karya dan orang", READING: "seorang peserta yang membaca dan mendokumentasikan karya", PERFORMANCE: "seorang peserta yang meneruskan persembahan dan latihan", EDUCATION: "seorang peserta yang meneruskan seni dan budaya melalui pengajaran dan pembelajaran", EVERYDAY: "seorang peserta yang meneruskan seni dan budaya dalam kehidupan harian", CULTURAL_RELATION: "seorang peserta yang terus berhubung dengan seni dan budaya" }, summary: "Salam ini disampaikan dengan membaca bersama arah yang dekat dalam kedua-dua rekod, peranan semasa dan arah hubungan yang dipilih. Kedudukan ini boleh berubah mengikut masa atau keadaan.", SAME_DIRECTION: "Satu arah yang dekat muncul dalam kedua-dua rekod.", ADJACENT_DIRECTION: "Sebahagian arah dalam dua rekod bersebelahan.", ROLE_BRIDGE: "Soalan yang serupa berterusan daripada peranan yang berbeza." },
};

let state = { loading: true, relay: null, error: "", result: "", translations: new Set() };
function c() { return copy[interfaceLanguageCode] || copy[String(interfaceLanguageCode).toLowerCase().startsWith("ko") ? "ko" : "en"]; }
function reasonCopy() { return greetingReasonCopy[interfaceLanguageCode] || greetingReasonCopy[String(interfaceLanguageCode).toLowerCase().startsWith("ko") ? "ko" : "en"]; }
function pointIndex(point) {
  const number = (key) => Number(String(point?.[key]?.code || point?.[key] || "").slice(1));
  const [m, s, d] = [number("m"), number("s"), number("d")];
  return m && s && d ? (m - 1) * 16 + (s - 1) * 4 + (d - 1) : -1;
}
function coordinateGraphic(thread) {
  const sender = pointIndex(thread.sender_coordinate || thread.connection_reason?.sender_point);
  const mine = pointIndex(thread.receiver_coordinate || thread.connection_reason?.receiver_point);
  if (sender < 0 && mine < 0) return "";
  return `<div class="greeting-coordinate-map"><div class="coordinate-grid" aria-label="${text(reasonCopy().map)}">${Array.from({ length: 64 }, (_, index) => `<span class="${index === sender ? "is-sender" : ""} ${index === mine ? "is-mine" : ""}"><i></i></span>`).join("")}</div><div class="coordinate-legend"><span><i class="mine-dot"></i>${text(c().mine)}</span><span><i class="sender-dot"></i>${text(c().sender)}</span></div></div>`;
}
function reasonSection(thread) {
  const reason = thread.connection_reason;
  if (!reason) return "";
  const structured = reason.version === "greeting-coordinate-reason-v3" && reason.summary_key === "CURATED_RECORD_CONNECTION";
  const localized = reasonCopy();
  const sender = structured ? localized.sender[reason.sender_context_code] : reason.sender_context;
  const summary = structured ? localized.summary : reason.summary;
  const evidence = structured
    ? (reason.evidence_codes || []).slice(0, 2).map((item) => localized[item?.type]).filter(Boolean)
    : (reason.evidence || []).slice(0, 2);
  return `<section class="relay-reason"><span>${text(c().reason)}</span>${sender ? `<strong>${text(sender)}</strong>` : ""}<p>${text(summary || "")}</p>${coordinateGraphic(thread)}${evidence.map((item) => `<small>${text(item)}</small>`).join("")}</section>`;
}
function messageCard(message) {
  const open = state.translations.has(message.id);
  return `<article class="relay-letter"><div class="relay-envelope" aria-hidden="true"><i></i><b></b><span></span></div><span>${text(c().original)} · ${text(message.source_language || "")}</span><p lang="${text(message.source_language || "")}">${text(message.body_original)}</p>${message.translated_body ? `<button class="translation-toggle" type="button" data-translation-id="${text(message.id)}" aria-expanded="${open}">${text(open ? c().hideTranslation : c().translation)}</button>${open ? `<div class="relay-translation" lang="${text(message.translation_language || "")}"><span>${text(message.translation_language || "")}</span><p>${text(message.translated_body)}</p></div>` : ""}` : ""}</article>`;
}
function render() {
  if (state.loading) { root.innerHTML = `<main class="relay-layout"><p>${text(c().loading)}</p></main>`; return; }
  if (state.error) { root.innerHTML = `<main class="relay-layout"><section class="relay-card"><div class="relay-project-mark" aria-hidden="true">39+</div><div class="archive-label">${text(c().label)}</div><h1>${text(c().error)}</h1></section></main>`; return; }
  if (state.result) { root.innerHTML = `<main class="relay-layout"><section class="relay-card"><div class="relay-project-mark" aria-hidden="true">39+</div><div class="archive-label">${text(c().label)}</div><h1>${text(state.result)}</h1></section></main>`; return; }
  const thread = state.relay.thread; const messages = thread.messages || [];
  root.innerHTML = `<main class="relay-layout"><section class="relay-card"><div class="relay-project-mark" aria-hidden="true">39+</div><div class="archive-label">${text(c().label)}</div><h1>${text(c().title)}</h1><p class="relay-lead">${text(c().lead)}</p>${reasonSection(thread)}<section class="relay-messages">${messages.map(messageCard).join("")}</section>${thread.can_reply ? `<section class="relay-reply"><h2>${text(c().replyTitle)}</h2><p>${text(c().replyHelp)}</p><textarea class="text-input" data-relay-message maxlength="1400" placeholder="${text(c().placeholder)}"></textarea><div class="relay-actions"><button class="secondary-button" data-relay-action="pass">${text(c().pass)}</button><button class="primary-button" data-relay-action="reply">${text(c().send)} <span aria-hidden="true">→</span></button></div><button class="relay-withdraw" data-relay-action="withdraw">${text(c().withdraw)}</button></section>` : ""}</section></main>`;
}
async function request(payload) {
  if (!endpoint || !token) throw new Error("RELAY_NOT_CONFIGURED");
  const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...payload, token }) });
  const body = await response.json().catch(() => ({}));
  if (!response.ok || !body.ok) throw new Error(body.error_code || "RELAY_REQUEST_FAILED");
  return body;
}

document.addEventListener("click", async (event) => {
  const translation = event.target.closest("[data-translation-id]");
  if (translation) { const id = translation.dataset.translationId; state.translations.has(id) ? state.translations.delete(id) : state.translations.add(id); render(); return; }
  const button = event.target.closest("[data-relay-action]"); if (!button) return;
  try {
    const action = button.dataset.relayAction;
    if (action === "pass") { await request({ action: "respond", intent: "pass" }); state.result = c().passed; }
    else if (action === "withdraw") { await request({ action: "respond", intent: "withdraw" }); state.result = c().withdrawn; }
    else { const message = document.querySelector("[data-relay-message]")?.value.trim() || ""; if (!message) return; await request({ action: "respond", intent: "reply", message, source_language: interfaceLanguageCode }); state.result = c().sent; }
  } catch { state.error = "RELAY_REQUEST_FAILED"; }
  render();
});

if (!token || !endpoint) { state.loading = false; state.error = "RELAY_NOT_CONFIGURED"; render(); }
else request({ action: "view" }).then((relay) => { state.relay = relay; state.loading = false; render(); }).catch(() => { state.loading = false; state.error = "RELAY_ACCESS_DENIED"; render(); });
